name: Pysparks CI/CD

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
    secrets:
      REGISTRY_SERVER:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - 
        name: Generate Tag Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          bump_each_commit: true
      -
        name: Add SHORT_SHA env property with commit short sha
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "TAG=${{ steps.version.outputs.version }}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/${{ inputs.project_path }}:${{ env.TAG }},${{ secrets.REGISTRY_SERVER }}/${{ inputs.project_path }}:latest
      # - 
      #   name: Request approval
      #   uses: trstringer/manual-approval@v1
      #   timeout-minutes: 60
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: ititandev
      #     issue-title: "Require approval to deploy ${{ env.PROJECT_FULLNAME }} version ${{steps.version.outputs.version}}"
      #     minimum-approvals: 1   
