name: Pysparks CI/CD

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      module: 
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'
      context:
        required: false
        type: string
        default: '.'
    secrets:
      REGISTRY_SERVER:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - 
        name: Generate Tag Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          bump_each_commit: true
      -
        name: Generate Image Tag
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "TAG=${{ steps.version.outputs.version }}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "NAMESPACE=`grep -e '^namespace' deploy/${{ inputs.module }}.yaml | awk '{print $2}'`" >> $GITHUB_ENV
      -
        name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          file: ${{ inputs.dockerfile }}
          tags: ${{ secrets.REGISTRY_SERVER }}/${{ inputs.project }}:${{ env.TAG }},${{ secrets.REGISTRY_SERVER }}/${{ inputs.project}}:latest
      - 
        uses: azure/setup-helm@v3
        with:
          version: '3.9.0' # default is latest (stable)
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      - 
        name: Helm deploy
        env:
          HELM_KUBECONFIG: ${{ secrets.HELM_KUBECONFIG }}
        run: |
          helm registry login pysparks.azurecr.io -u ${{ secrets.HELM_USERNAME }} -p ${{ secrets.HELM_PASSWORD }}
          mkdir -p ~/.kube
          printf "$HELM_KUBECONFIG" > ~/.kube/config
          helm upgrade ${{ inputs.module }} -i -f deploy/${{ inputs.module }}.yaml oci://pysparks.azurecr.io/chart/common --version ${{ secrets.COMMON_CHART_VERSION }} -n ${{ env.NAMESPACE }} --set image=${{ secrets.REGISTRY_SERVER }}/${{ inputs.project }}:${{ env.TAG }}
      # - 
      #   name: Request approval
      #   uses: trstringer/manual-approval@v1
      #   timeout-minutes: 60
      #   with:
      #     secret: ${{ github.TOKEN }}
      #     approvers: ititandev
      #     issue-title: "Require approval to deploy ${{ env.PROJECT_FULLNAME }} version ${{steps.version.outputs.version}}"
      #     minimum-approvals: 1   
